name: daily_update
on:
  schedule:
    
    - cron: "0 21 * * *"
  workflow_dispatch:

permissions:                    # Global permissions configuration starts here
  contents: read                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    continue-on-error: true

  
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
         sparse-checkout: |
          .github
           config
         
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/Brisppy/twitch-archiver       

      - name: DL CHATS
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          twitch-archiver -D --config-dir ./config/ --archive-only --chat -c ${{ secrets.CH }} -d ./output




      - name: PUSH
        if: always()
        run: |
          git add .
          timestamp=$(date -u)
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" 
          git status || exit 0
         
          
      - name: Push changes # push the output folder to your repo, turn on workflow read and write permission
        if: always()
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.WW2 }}
         force: true
